/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutTemplateBuilderRouteImport } from './routes/_layout/template-builder'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutInvoicesRouteImport } from './routes/_layout/invoices'
import { Route as LayoutInvoiceTemplatesRouteImport } from './routes/_layout/invoice-templates'
import { Route as LayoutInvoiceHistoryRouteImport } from './routes/_layout/invoice-history'
import { Route as LayoutInsightsRouteImport } from './routes/_layout/insights'
import { Route as LayoutDataTablesRouteImport } from './routes/_layout/data-tables'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCustomersRouteImport } from './routes/_layout/customers'
import { Route as LayoutCreateInvoiceRouteImport } from './routes/_layout/create-invoice'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutItemsIndexRouteImport } from './routes/_layout/items/index'
import { Route as LayoutInvoiceHistoryIndexRouteImport } from './routes/_layout/invoice-history/index'
import { Route as LayoutDataTablesIndexRouteImport } from './routes/_layout/data-tables/index'
import { Route as LayoutCustomersIndexRouteImport } from './routes/_layout/customers/index'
import { Route as LayoutItemsItemIdRouteImport } from './routes/_layout/items.$itemId'
import { Route as LayoutInvoiceHistoryInvoiceIdRouteImport } from './routes/_layout/invoice-history.$invoiceId'
import { Route as LayoutDataTablesNewRouteImport } from './routes/_layout/data-tables.new'
import { Route as LayoutDataTablesTableIdRouteImport } from './routes/_layout/data-tables.$tableId'
import { Route as LayoutCustomersCustomerIdRouteImport } from './routes/_layout/customers.$customerId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
})
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
})
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const LayoutTemplateBuilderRoute = LayoutTemplateBuilderRouteImport.update({
  id: '/template-builder',
  path: '/template-builder',
  getParentRoute: () => LayoutRoute,
})
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
})
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
})
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
})
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
})
const LayoutInvoicesRoute = LayoutInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => LayoutRoute,
})
const LayoutInvoiceTemplatesRoute = LayoutInvoiceTemplatesRouteImport.update({
  id: '/invoice-templates',
  path: '/invoice-templates',
  getParentRoute: () => LayoutRoute,
})
const LayoutInvoiceHistoryRoute = LayoutInvoiceHistoryRouteImport.update({
  id: '/invoice-history',
  path: '/invoice-history',
  getParentRoute: () => LayoutRoute,
})
const LayoutInsightsRoute = LayoutInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LayoutRoute,
})
const LayoutDataTablesRoute = LayoutDataTablesRouteImport.update({
  id: '/data-tables',
  path: '/data-tables',
  getParentRoute: () => LayoutRoute,
})
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
})
const LayoutCustomersRoute = LayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
})
const LayoutCreateInvoiceRoute = LayoutCreateInvoiceRouteImport.update({
  id: '/create-invoice',
  path: '/create-invoice',
  getParentRoute: () => LayoutRoute,
})
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
})
const LayoutItemsIndexRoute = LayoutItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutItemsRoute,
})
const LayoutInvoiceHistoryIndexRoute =
  LayoutInvoiceHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutInvoiceHistoryRoute,
  })
const LayoutDataTablesIndexRoute = LayoutDataTablesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDataTablesRoute,
})
const LayoutCustomersIndexRoute = LayoutCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCustomersRoute,
})
const LayoutItemsItemIdRoute = LayoutItemsItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => LayoutItemsRoute,
})
const LayoutInvoiceHistoryInvoiceIdRoute =
  LayoutInvoiceHistoryInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => LayoutInvoiceHistoryRoute,
  })
const LayoutDataTablesNewRoute = LayoutDataTablesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutDataTablesRoute,
})
const LayoutDataTablesTableIdRoute = LayoutDataTablesTableIdRouteImport.update({
  id: '/$tableId',
  path: '/$tableId',
  getParentRoute: () => LayoutDataTablesRoute,
})
const LayoutCustomersCustomerIdRoute =
  LayoutCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => LayoutCustomersRoute,
  })

const LayoutCustomersRouteChildren = {
  LayoutCustomersCustomerIdRoute: LayoutCustomersCustomerIdRoute,
  LayoutCustomersIndexRoute: LayoutCustomersIndexRoute,
}

const LayoutCustomersRouteWithChildren = LayoutCustomersRoute._addFileChildren(
  LayoutCustomersRouteChildren,
)

const LayoutDataTablesRouteChildren = {
  LayoutDataTablesTableIdRoute: LayoutDataTablesTableIdRoute,
  LayoutDataTablesNewRoute: LayoutDataTablesNewRoute,
  LayoutDataTablesIndexRoute: LayoutDataTablesIndexRoute,
}

const LayoutDataTablesRouteWithChildren =
  LayoutDataTablesRoute._addFileChildren(LayoutDataTablesRouteChildren)

const LayoutInvoiceHistoryRouteChildren = {
  LayoutInvoiceHistoryInvoiceIdRoute: LayoutInvoiceHistoryInvoiceIdRoute,
  LayoutInvoiceHistoryIndexRoute: LayoutInvoiceHistoryIndexRoute,
}

const LayoutInvoiceHistoryRouteWithChildren =
  LayoutInvoiceHistoryRoute._addFileChildren(LayoutInvoiceHistoryRouteChildren)

const LayoutItemsRouteChildren = {
  LayoutItemsItemIdRoute: LayoutItemsItemIdRoute,
  LayoutItemsIndexRoute: LayoutItemsIndexRoute,
}

const LayoutItemsRouteWithChildren = LayoutItemsRoute._addFileChildren(
  LayoutItemsRouteChildren,
)

const LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCreateInvoiceRoute: LayoutCreateInvoiceRoute,
  LayoutCustomersRoute: LayoutCustomersRouteWithChildren,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutDataTablesRoute: LayoutDataTablesRouteWithChildren,
  LayoutInsightsRoute: LayoutInsightsRoute,
  LayoutInvoiceHistoryRoute: LayoutInvoiceHistoryRouteWithChildren,
  LayoutInvoiceTemplatesRoute: LayoutInvoiceTemplatesRoute,
  LayoutInvoicesRoute: LayoutInvoicesRoute,
  LayoutItemsRoute: LayoutItemsRouteWithChildren,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTemplateBuilderRoute: LayoutTemplateBuilderRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
