// This file is auto-generated by @hey-api/openapi-ts

export const AdminUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email_confirm: {
            type: 'boolean',
            title: 'Email Confirm',
            default: true
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'AdminUserCreate'
} as const;

export const AdminUserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        ban_duration: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ban Duration'
        }
    },
    type: 'object',
    title: 'AdminUserUpdate'
} as const;

export const AuthIdentitySchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        identity_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Identity Data'
        }
    },
    type: 'object',
    required: ['id', 'provider'],
    title: 'AuthIdentity'
} as const;

export const AuthResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refresh Token'
        },
        expires_in: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires In'
        },
        user: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'AuthResponse'
} as const;

export const AuthSessionSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        user_agent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Agent'
        },
        ip: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip'
        },
        is_current: {
            type: 'boolean',
            title: 'Is Current',
            default: false
        }
    },
    type: 'object',
    required: ['id'],
    title: 'AuthSession'
} as const;

export const CompanySettingsCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        gstin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gstin'
        },
        pan: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pan'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        pincode: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pincode'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        website: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        signature_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Signature Url'
        },
        bank_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Name'
        },
        bank_account: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Account'
        },
        bank_ifsc: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Ifsc'
        },
        bank_branch: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Branch'
        },
        upi_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upi Id'
        },
        terms_and_conditions: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Terms And Conditions'
        },
        invoice_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Invoice Prefix',
            default: 'INV-'
        },
        quotation_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Quotation Prefix',
            default: 'QUO-'
        },
        proforma_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Proforma Prefix',
            default: 'PRO-'
        },
        challan_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Challan Prefix',
            default: 'CHL-'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CompanySettingsCreate'
} as const;

export const CompanySettingsPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        gstin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gstin'
        },
        pan: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pan'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        pincode: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pincode'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        website: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        signature_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Signature Url'
        },
        bank_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Name'
        },
        bank_account: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Account'
        },
        bank_ifsc: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Ifsc'
        },
        bank_branch: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Branch'
        },
        upi_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upi Id'
        },
        terms_and_conditions: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Terms And Conditions'
        },
        invoice_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Invoice Prefix',
            default: 'INV-'
        },
        quotation_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Quotation Prefix',
            default: 'QUO-'
        },
        proforma_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Proforma Prefix',
            default: 'PRO-'
        },
        challan_prefix: {
            type: 'string',
            maxLength: 20,
            title: 'Challan Prefix',
            default: 'CHL-'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'CompanySettingsPublic'
} as const;

export const CompanySettingsUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        gstin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gstin'
        },
        pan: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pan'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        pincode: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pincode'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        website: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        signature_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Signature Url'
        },
        bank_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Name'
        },
        bank_account: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Account'
        },
        bank_ifsc: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Ifsc'
        },
        bank_branch: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Branch'
        },
        upi_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upi Id'
        },
        terms_and_conditions: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Terms And Conditions'
        },
        invoice_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Prefix'
        },
        quotation_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quotation Prefix'
        },
        proforma_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proforma Prefix'
        },
        challan_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Challan Prefix'
        }
    },
    type: 'object',
    title: 'CompanySettingsUpdate'
} as const;

export const CustomerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        party_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Party Type',
            default: 'customer'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        whatsapp: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        billing_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Billing Address'
        },
        shipping_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Address'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        gstin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gstin'
        },
        gst: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gst'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        opening_balance: {
            type: 'number',
            title: 'Opening Balance',
            default: 0
        },
        credit_limit: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credit Limit'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CustomerCreate'
} as const;

export const CustomerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        party_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Party Type',
            default: 'customer'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        whatsapp: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        billing_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Billing Address'
        },
        shipping_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Address'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        gstin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gstin'
        },
        gst: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gst'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        opening_balance: {
            type: 'number',
            title: 'Opening Balance',
            default: 0
        },
        credit_limit: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credit Limit'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'CustomerPublic'
} as const;

export const CustomerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        party_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Party Type'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        whatsapp: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        billing_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Billing Address'
        },
        shipping_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Address'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        gstin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gstin'
        },
        gst: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gst'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        opening_balance: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opening Balance'
        },
        credit_limit: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credit Limit'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CustomerUpdate'
} as const;

export const CustomersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CustomerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CustomersPublic'
} as const;

export const DashboardStatsSchema = {
    properties: {
        total_invoices: {
            type: 'integer',
            title: 'Total Invoices',
            default: 0
        },
        paid_count: {
            type: 'integer',
            title: 'Paid Count',
            default: 0
        },
        unpaid_count: {
            type: 'integer',
            title: 'Unpaid Count',
            default: 0
        },
        overdue_count: {
            type: 'integer',
            title: 'Overdue Count',
            default: 0
        },
        total_customers: {
            type: 'integer',
            title: 'Total Customers',
            default: 0
        },
        total_revenue: {
            type: 'number',
            title: 'Total Revenue',
            default: 0
        }
    },
    type: 'object',
    title: 'DashboardStats'
} as const;

export const DataTableColumnSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Type'
        },
        mandatory: {
            type: 'boolean',
            title: 'Mandatory',
            default: false
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Options'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'DataTableColumn'
} as const;

export const DataTableCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            items: {
                '$ref': '#/components/schemas/DataTableColumn'
            },
            type: 'array',
            title: 'Columns'
        }
    },
    type: 'object',
    required: ['name', 'columns'],
    title: 'DataTableCreate'
} as const;

export const DataTablePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Columns'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'columns', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'DataTablePublic'
} as const;

export const DataTableUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/DataTableColumn'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Columns'
        }
    },
    type: 'object',
    title: 'DataTableUpdate'
} as const;

export const DataTableWithRowsSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Columns'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        rows: {
            items: {
                '$ref': '#/components/schemas/TableRowPublic'
            },
            type: 'array',
            title: 'Rows'
        },
        reminders: {
            items: {
                '$ref': '#/components/schemas/TableReminderPublic'
            },
            type: 'array',
            title: 'Reminders'
        }
    },
    type: 'object',
    required: ['name', 'columns', 'id', 'owner_id', 'created_at', 'updated_at', 'rows', 'reminders'],
    title: 'DataTableWithRows'
} as const;

export const DocumentTypeSchema = {
    type: 'string',
    enum: ['invoice', 'quotation', 'proforma', 'challan'],
    title: 'DocumentType'
} as const;

export const EmailRequestSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'EmailRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InvoiceCreateSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            maxLength: 50,
            title: 'Invoice Number'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType',
            default: 'invoice'
        },
        invoice_date: {
            type: 'string',
            format: 'date',
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        valid_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valid Until'
        },
        currency: {
            type: 'string',
            maxLength: 10,
            title: 'Currency',
            default: 'INR'
        },
        subtotal: {
            type: 'number',
            title: 'Subtotal',
            default: 0
        },
        total_tax: {
            type: 'number',
            title: 'Total Tax',
            default: 0
        },
        grand_total: {
            type: 'number',
            title: 'Grand Total',
            default: 0
        },
        discount: {
            type: 'number',
            title: 'Discount',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            '$ref': '#/components/schemas/InvoiceStatus',
            default: 'unpaid'
        },
        place_of_supply: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Of Supply'
        },
        reverse_charge: {
            type: 'boolean',
            title: 'Reverse Charge',
            default: false
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/InvoiceItemData'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['invoice_number', 'invoice_date', 'customer_id'],
    title: 'InvoiceCreate'
} as const;

export const InvoiceItemDataSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        quantity: {
            type: 'number',
            title: 'Quantity',
            default: 1
        },
        price: {
            type: 'number',
            title: 'Price',
            default: 0
        },
        tax: {
            type: 'number',
            title: 'Tax',
            default: 0
        },
        unit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit'
        },
        hsn_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hsn Code'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'InvoiceItemData'
} as const;

export const InvoicePublicSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            maxLength: 50,
            title: 'Invoice Number'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType',
            default: 'invoice'
        },
        invoice_date: {
            type: 'string',
            format: 'date',
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        valid_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valid Until'
        },
        currency: {
            type: 'string',
            maxLength: 10,
            title: 'Currency',
            default: 'INR'
        },
        subtotal: {
            type: 'number',
            title: 'Subtotal',
            default: 0
        },
        total_tax: {
            type: 'number',
            title: 'Total Tax',
            default: 0
        },
        grand_total: {
            type: 'number',
            title: 'Grand Total',
            default: 0
        },
        discount: {
            type: 'number',
            title: 'Discount',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            '$ref': '#/components/schemas/InvoiceStatus',
            default: 'unpaid'
        },
        place_of_supply: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Of Supply'
        },
        reverse_charge: {
            type: 'boolean',
            title: 'Reverse Charge',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/InvoiceItemData'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['invoice_number', 'invoice_date', 'id', 'owner_id', 'customer_id', 'created_at', 'updated_at'],
    title: 'InvoicePublic'
} as const;

export const InvoiceStatusSchema = {
    type: 'string',
    enum: ['unpaid', 'paid', 'overdue', 'draft', 'expired', 'accepted', 'rejected'],
    title: 'InvoiceStatus'
} as const;

export const InvoiceTemplateCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        kind: {
            '$ref': '#/components/schemas/InvoiceTemplateKind'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: false
        },
        built_in_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Built In Id'
        },
        custom_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Data'
        },
        imported_html: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported Html'
        },
        imported_pdf_data_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported Pdf Data Url'
        }
    },
    type: 'object',
    required: ['name', 'kind'],
    title: 'InvoiceTemplateCreate'
} as const;

export const InvoiceTemplateKindSchema = {
    type: 'string',
    enum: ['built_in', 'custom', 'imported_html', 'imported_pdf'],
    title: 'InvoiceTemplateKind'
} as const;

export const InvoiceTemplatePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        kind: {
            '$ref': '#/components/schemas/InvoiceTemplateKind'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: false
        },
        built_in_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Built In Id'
        },
        custom_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Data'
        },
        imported_html: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported Html'
        },
        imported_pdf_data_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported Pdf Data Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'kind', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'InvoiceTemplatePublic'
} as const;

export const InvoiceTemplateUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        kind: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InvoiceTemplateKind'
                },
                {
                    type: 'null'
                }
            ]
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        built_in_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Built In Id'
        },
        custom_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Data'
        },
        imported_html: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported Html'
        },
        imported_pdf_data_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imported Pdf Data Url'
        }
    },
    type: 'object',
    title: 'InvoiceTemplateUpdate'
} as const;

export const InvoiceTemplatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InvoiceTemplatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InvoiceTemplatesPublic'
} as const;

export const InvoiceUpdateSchema = {
    properties: {
        invoice_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Number'
        },
        document_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DocumentType'
                },
                {
                    type: 'null'
                }
            ]
        },
        invoice_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        valid_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valid Until'
        },
        currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        subtotal: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subtotal'
        },
        total_tax: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Tax'
        },
        grand_total: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grand Total'
        },
        discount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discount'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InvoiceStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        place_of_supply: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Of Supply'
        },
        reverse_charge: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reverse Charge'
        },
        customer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Id'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/InvoiceItemData'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'InvoiceUpdate'
} as const;

export const InvoiceWithCustomerSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            maxLength: 50,
            title: 'Invoice Number'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType',
            default: 'invoice'
        },
        invoice_date: {
            type: 'string',
            format: 'date',
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        valid_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valid Until'
        },
        currency: {
            type: 'string',
            maxLength: 10,
            title: 'Currency',
            default: 'INR'
        },
        subtotal: {
            type: 'number',
            title: 'Subtotal',
            default: 0
        },
        total_tax: {
            type: 'number',
            title: 'Total Tax',
            default: 0
        },
        grand_total: {
            type: 'number',
            title: 'Grand Total',
            default: 0
        },
        discount: {
            type: 'number',
            title: 'Discount',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            '$ref': '#/components/schemas/InvoiceStatus',
            default: 'unpaid'
        },
        place_of_supply: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Of Supply'
        },
        reverse_charge: {
            type: 'boolean',
            title: 'Reverse Charge',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/InvoiceItemData'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        customer: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CustomerPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['invoice_number', 'invoice_date', 'id', 'owner_id', 'customer_id', 'created_at', 'updated_at'],
    title: 'InvoiceWithCustomer'
} as const;

export const InvoicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InvoicePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InvoicesPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        unit: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit'
        },
        price: {
            type: 'number',
            title: 'Price',
            default: 0
        },
        tax_rate: {
            type: 'number',
            title: 'Tax Rate',
            default: 0
        },
        stock: {
            type: 'number',
            title: 'Stock',
            default: 0
        },
        low_stock_threshold: {
            type: 'number',
            title: 'Low Stock Threshold',
            default: 5
        },
        stock_history: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Stock History'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        unit: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit'
        },
        price: {
            type: 'number',
            title: 'Price',
            default: 0
        },
        tax_rate: {
            type: 'number',
            title: 'Tax Rate',
            default: 0
        },
        stock: {
            type: 'number',
            title: 'Stock',
            default: 0
        },
        low_stock_threshold: {
            type: 'number',
            title: 'Low Stock Threshold',
            default: 5
        },
        stock_history: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Stock History'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        unit: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        tax_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tax Rate'
        },
        stock: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock'
        },
        low_stock_threshold: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Low Stock Threshold'
        },
        stock_history: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock History'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LoginRequestSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'LoginRequest'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NotificationCreateSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/NotificationType',
            default: 'info'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        table_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Table Id'
        },
        table_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Table Name'
        },
        row_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Row Id'
        },
        row_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Row Label'
        },
        read: {
            type: 'boolean',
            title: 'Read',
            default: false
        },
        scheduled_for: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scheduled For'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'NotificationCreate'
} as const;

export const NotificationPublicSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/NotificationType',
            default: 'info'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        table_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Table Id'
        },
        table_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Table Name'
        },
        row_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Row Id'
        },
        row_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Row Label'
        },
        read: {
            type: 'boolean',
            title: 'Read',
            default: false
        },
        scheduled_for: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scheduled For'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id', 'created_at'],
    title: 'NotificationPublic'
} as const;

export const NotificationTypeSchema = {
    type: 'string',
    enum: ['reminder', 'due_date', 'expiry', 'info'],
    title: 'NotificationType'
} as const;

export const NotificationUpdateSchema = {
    properties: {
        read: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Read'
        }
    },
    type: 'object',
    title: 'NotificationUpdate'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        unread_count: {
            type: 'integer',
            title: 'Unread Count'
        }
    },
    type: 'object',
    required: ['data', 'count', 'unread_count'],
    title: 'NotificationsPublic'
} as const;

export const OAuthURLResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        }
    },
    type: 'object',
    required: ['url', 'provider'],
    title: 'OAuthURLResponse'
} as const;

export const PaginatedResponse_DataTablePublic_Schema = {
    properties: {
        data: {
            items: {},
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'page_size', 'total_pages'],
    title: 'PaginatedResponse[DataTablePublic]'
} as const;

export const PaginatedResponse_UserPublic_Schema = {
    properties: {
        data: {
            items: {},
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'page_size', 'total_pages'],
    title: 'PaginatedResponse[UserPublic]'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProfilePublicSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'email'],
    title: 'ProfilePublic'
} as const;

export const ProfilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProfilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProfilesPublic'
} as const;

export const TableReminderCreateSchema = {
    properties: {
        reminder_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Reminder Data'
        }
    },
    type: 'object',
    required: ['reminder_data'],
    title: 'TableReminderCreate'
} as const;

export const TableReminderPublicSchema = {
    properties: {
        reminder_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Reminder Data'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        table_id: {
            type: 'string',
            format: 'uuid',
            title: 'Table Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['reminder_data', 'id', 'table_id', 'created_at'],
    title: 'TableReminderPublic'
} as const;

export const TableRowCreateSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TableRowCreate'
} as const;

export const TableRowPublicSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        table_id: {
            type: 'string',
            format: 'uuid',
            title: 'Table Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['data', 'id', 'table_id', 'created_at'],
    title: 'TableRowPublic'
} as const;

export const TableRowUpdateSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TableRowUpdate'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['new_password'],
    title: 'UpdatePassword'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'email'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;