// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CustomerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        gst: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gst'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CustomerCreate'
} as const;

export const CustomerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        gst: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gst'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'CustomerPublic'
} as const;

export const CustomerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        gst: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gst'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CustomerUpdate'
} as const;

export const CustomersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CustomerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CustomersPublic'
} as const;

export const DashboardStatsSchema = {
    properties: {
        total_invoices: {
            type: 'integer',
            title: 'Total Invoices',
            default: 0
        },
        paid_count: {
            type: 'integer',
            title: 'Paid Count',
            default: 0
        },
        unpaid_count: {
            type: 'integer',
            title: 'Unpaid Count',
            default: 0
        },
        overdue_count: {
            type: 'integer',
            title: 'Overdue Count',
            default: 0
        },
        total_customers: {
            type: 'integer',
            title: 'Total Customers',
            default: 0
        },
        total_revenue: {
            type: 'number',
            title: 'Total Revenue',
            default: 0
        }
    },
    type: 'object',
    title: 'DashboardStats'
} as const;

export const DataTableColumnSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        type: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Type'
        },
        mandatory: {
            type: 'boolean',
            title: 'Mandatory',
            default: false
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Options'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'DataTableColumn'
} as const;

export const DataTableCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            items: {
                '$ref': '#/components/schemas/DataTableColumn'
            },
            type: 'array',
            title: 'Columns'
        }
    },
    type: 'object',
    required: ['name', 'columns'],
    title: 'DataTableCreate'
} as const;

export const DataTablePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Columns'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'columns', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'DataTablePublic'
} as const;

export const DataTableUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/DataTableColumn'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Columns'
        }
    },
    type: 'object',
    title: 'DataTableUpdate'
} as const;

export const DataTableWithRowsSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        columns: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Columns'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        rows: {
            items: {
                '$ref': '#/components/schemas/TableRowPublic'
            },
            type: 'array',
            title: 'Rows'
        },
        reminders: {
            items: {
                '$ref': '#/components/schemas/TableReminderPublic'
            },
            type: 'array',
            title: 'Reminders'
        }
    },
    type: 'object',
    required: ['name', 'columns', 'id', 'owner_id', 'created_at', 'updated_at', 'rows', 'reminders'],
    title: 'DataTableWithRows'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InvoiceCreateSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            maxLength: 50,
            title: 'Invoice Number'
        },
        invoice_date: {
            type: 'string',
            format: 'date',
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        currency: {
            type: 'string',
            maxLength: 10,
            title: 'Currency',
            default: 'INR'
        },
        subtotal: {
            type: 'number',
            title: 'Subtotal',
            default: 0
        },
        total_tax: {
            type: 'number',
            title: 'Total Tax',
            default: 0
        },
        grand_total: {
            type: 'number',
            title: 'Grand Total',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            '$ref': '#/components/schemas/InvoiceStatus',
            default: 'unpaid'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/InvoiceItemData'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['invoice_number', 'invoice_date', 'customer_id'],
    title: 'InvoiceCreate'
} as const;

export const InvoiceItemDataSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        quantity: {
            type: 'number',
            title: 'Quantity',
            default: 1
        },
        price: {
            type: 'number',
            title: 'Price',
            default: 0
        },
        tax: {
            type: 'number',
            title: 'Tax',
            default: 0
        }
    },
    type: 'object',
    required: ['name'],
    title: 'InvoiceItemData',
    description: 'Schema for a single line item embedded in the invoice JSONB.'
} as const;

export const InvoicePublicSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            maxLength: 50,
            title: 'Invoice Number'
        },
        invoice_date: {
            type: 'string',
            format: 'date',
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        currency: {
            type: 'string',
            maxLength: 10,
            title: 'Currency',
            default: 'INR'
        },
        subtotal: {
            type: 'number',
            title: 'Subtotal',
            default: 0
        },
        total_tax: {
            type: 'number',
            title: 'Total Tax',
            default: 0
        },
        grand_total: {
            type: 'number',
            title: 'Grand Total',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            '$ref': '#/components/schemas/InvoiceStatus',
            default: 'unpaid'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/InvoiceItemData'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['invoice_number', 'invoice_date', 'id', 'owner_id', 'customer_id', 'created_at', 'updated_at'],
    title: 'InvoicePublic'
} as const;

export const InvoiceStatusSchema = {
    type: 'string',
    enum: ['unpaid', 'paid', 'overdue'],
    title: 'InvoiceStatus'
} as const;

export const InvoiceUpdateSchema = {
    properties: {
        invoice_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        subtotal: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subtotal'
        },
        total_tax: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Tax'
        },
        grand_total: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grand Total'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InvoiceStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        customer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Id'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/InvoiceItemData'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'InvoiceUpdate'
} as const;

export const InvoiceWithCustomerSchema = {
    properties: {
        invoice_number: {
            type: 'string',
            maxLength: 50,
            title: 'Invoice Number'
        },
        invoice_date: {
            type: 'string',
            format: 'date',
            title: 'Invoice Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        currency: {
            type: 'string',
            maxLength: 10,
            title: 'Currency',
            default: 'INR'
        },
        subtotal: {
            type: 'number',
            title: 'Subtotal',
            default: 0
        },
        total_tax: {
            type: 'number',
            title: 'Total Tax',
            default: 0
        },
        grand_total: {
            type: 'number',
            title: 'Grand Total',
            default: 0
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        payment_terms: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Terms'
        },
        status: {
            '$ref': '#/components/schemas/InvoiceStatus',
            default: 'unpaid'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/InvoiceItemData'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        customer: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CustomerPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['invoice_number', 'invoice_date', 'id', 'owner_id', 'customer_id', 'created_at', 'updated_at'],
    title: 'InvoiceWithCustomer'
} as const;

export const InvoicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InvoicePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InvoicesPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PaginatedResponse_DataTablePublic_Schema = {
    properties: {
        data: {
            items: {},
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: ['data', 'total', 'page', 'page_size', 'total_pages'],
    title: 'PaginatedResponse[DataTablePublic]'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TableReminderCreateSchema = {
    properties: {
        reminder_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Reminder Data'
        }
    },
    type: 'object',
    required: ['reminder_data'],
    title: 'TableReminderCreate'
} as const;

export const TableReminderPublicSchema = {
    properties: {
        reminder_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Reminder Data'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        table_id: {
            type: 'string',
            format: 'uuid',
            title: 'Table Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['reminder_data', 'id', 'table_id', 'created_at'],
    title: 'TableReminderPublic'
} as const;

export const TableRowCreateSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TableRowCreate'
} as const;

export const TableRowPublicSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        table_id: {
            type: 'string',
            format: 'uuid',
            title: 'Table Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['data', 'id', 'table_id', 'created_at'],
    title: 'TableRowPublic'
} as const;

export const TableRowUpdateSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'TableRowUpdate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;