// This file is auto-generated by @hey-api/openapi-ts

export type AdminUserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    is_superuser?: boolean;
};

export type AdminUserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_superuser?: (boolean | null);
    is_active?: (boolean | null);
};

export type AuthResponse = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
    expires_in?: (number | null);
    user?: (UserPublic | null);
};

export type Body_invoice_templates_parse_excel_preview = {
    file: string;
};

export type BulkDeleteResponse = {
    deleted: number;
};

export type CompanySettingsCreate = {
    name: string;
    gstin?: (string | null);
    pan?: (string | null);
    address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    pincode?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
    signature_url?: (string | null);
    bank_name?: (string | null);
    bank_account?: (string | null);
    bank_ifsc?: (string | null);
    bank_branch?: (string | null);
    upi_id?: (string | null);
    terms_and_conditions?: (string | null);
    invoice_prefix?: string;
    quotation_prefix?: string;
    proforma_prefix?: string;
    challan_prefix?: string;
    whatsapp_enabled?: boolean;
    openwa_base_url?: string;
    openwa_api_key?: (string | null);
    openwa_session_id?: (string | null);
    smtp_host?: (string | null);
    smtp_port?: number;
    smtp_user?: (string | null);
    smtp_password?: (string | null);
    smtp_tls?: boolean;
    emails_from_email?: (string | null);
    emails_from_name?: (string | null);
};

export type CompanySettingsPublic = {
    name: string;
    gstin?: (string | null);
    pan?: (string | null);
    address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    pincode?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
    signature_url?: (string | null);
    bank_name?: (string | null);
    bank_account?: (string | null);
    bank_ifsc?: (string | null);
    bank_branch?: (string | null);
    upi_id?: (string | null);
    terms_and_conditions?: (string | null);
    invoice_prefix?: string;
    quotation_prefix?: string;
    proforma_prefix?: string;
    challan_prefix?: string;
    whatsapp_enabled?: boolean;
    openwa_base_url?: string;
    openwa_api_key?: (string | null);
    openwa_session_id?: (string | null);
    smtp_host?: (string | null);
    smtp_port?: number;
    smtp_user?: (string | null);
    smtp_password?: (string | null);
    smtp_tls?: boolean;
    emails_from_email?: (string | null);
    emails_from_name?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type CompanySettingsUpdate = {
    name?: (string | null);
    gstin?: (string | null);
    pan?: (string | null);
    address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    pincode?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    website?: (string | null);
    logo_url?: (string | null);
    signature_url?: (string | null);
    bank_name?: (string | null);
    bank_account?: (string | null);
    bank_ifsc?: (string | null);
    bank_branch?: (string | null);
    upi_id?: (string | null);
    terms_and_conditions?: (string | null);
    invoice_prefix?: (string | null);
    quotation_prefix?: (string | null);
    proforma_prefix?: (string | null);
    challan_prefix?: (string | null);
    whatsapp_enabled?: (boolean | null);
    openwa_base_url?: (string | null);
    openwa_api_key?: (string | null);
    openwa_session_id?: (string | null);
    smtp_host?: (string | null);
    smtp_port?: (number | null);
    smtp_user?: (string | null);
    smtp_password?: (string | null);
    smtp_tls?: (boolean | null);
    emails_from_email?: (string | null);
    emails_from_name?: (string | null);
};

export type CustomerCreate = {
    name: string;
    party_type?: (string | null);
    phone?: (string | null);
    whatsapp?: (string | null);
    email?: (string | null);
    billing_address?: (string | null);
    shipping_address?: (string | null);
    address?: (string | null);
    gstin?: (string | null);
    gst?: (string | null);
    state?: (string | null);
    tags?: Array<(string)>;
    opening_balance?: number;
    credit_limit?: (number | null);
    payment_terms?: (string | null);
    notes?: (string | null);
};

export type CustomerPublic = {
    name: string;
    party_type?: (string | null);
    phone?: (string | null);
    whatsapp?: (string | null);
    email?: (string | null);
    billing_address?: (string | null);
    shipping_address?: (string | null);
    address?: (string | null);
    gstin?: (string | null);
    gst?: (string | null);
    state?: (string | null);
    tags?: Array<(string)>;
    opening_balance?: number;
    credit_limit?: (number | null);
    payment_terms?: (string | null);
    notes?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type CustomersPublic = {
    data: Array<CustomerPublic>;
    count: number;
};

export type CustomerUpdate = {
    name?: (string | null);
    party_type?: (string | null);
    phone?: (string | null);
    whatsapp?: (string | null);
    email?: (string | null);
    billing_address?: (string | null);
    shipping_address?: (string | null);
    address?: (string | null);
    gstin?: (string | null);
    gst?: (string | null);
    state?: (string | null);
    tags?: (Array<(string)> | null);
    opening_balance?: (number | null);
    credit_limit?: (number | null);
    payment_terms?: (string | null);
    notes?: (string | null);
};

export type DashboardStats = {
    total_invoices?: number;
    paid_count?: number;
    unpaid_count?: number;
    overdue_count?: number;
    total_customers?: number;
    total_revenue?: number;
};

export type DataTableColumn = {
    name: string;
    description?: (string | null);
    type: string;
    mandatory?: boolean;
    options?: Array<(string)>;
};

export type DataTableCreate = {
    name: string;
    description?: (string | null);
    columns: Array<DataTableColumn>;
};

export type DataTablePublic = {
    name: string;
    description?: (string | null);
    columns: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type DataTableUpdate = {
    name?: (string | null);
    description?: (string | null);
    columns?: (Array<DataTableColumn> | null);
};

export type DataTableWithRows = {
    name: string;
    description?: (string | null);
    columns: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    rows: Array<TableRowPublic>;
    reminders: Array<TableReminderPublic>;
};

export type DocumentType = 'invoice' | 'quotation' | 'proforma' | 'challan';

export type ExcelParseResponse = {
    columns: Array<unknown>;
    column_mapping: {
        [key: string]: (number);
    };
    data: Array<{
        [key: string]: unknown;
    }>;
    total_rows: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InvoiceCreate = {
    invoice_number: string;
    document_type?: DocumentType;
    invoice_date: string;
    due_date?: (string | null);
    valid_until?: (string | null);
    currency?: string;
    subtotal?: number;
    total_tax?: number;
    grand_total?: number;
    discount?: number;
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: InvoiceStatus;
    place_of_supply?: (string | null);
    reverse_charge?: boolean;
    customer_id: string;
    items?: Array<InvoiceItemData>;
};

export type InvoiceItemData = {
    name: string;
    description?: (string | null);
    quantity?: number;
    price?: number;
    tax?: number;
    unit?: (string | null);
    hsn_code?: (string | null);
};

export type InvoicePublic = {
    invoice_number: string;
    document_type?: DocumentType;
    invoice_date: string;
    due_date?: (string | null);
    valid_until?: (string | null);
    currency?: string;
    subtotal?: number;
    total_tax?: number;
    grand_total?: number;
    discount?: number;
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: InvoiceStatus;
    place_of_supply?: (string | null);
    reverse_charge?: boolean;
    id: string;
    owner_id: string;
    customer_id: string;
    items?: Array<InvoiceItemData>;
    created_at: string;
    updated_at: string;
};

export type InvoicesPublic = {
    data: Array<InvoicePublic>;
    count: number;
};

export type InvoiceStatus = 'unpaid' | 'paid' | 'overdue' | 'draft' | 'expired' | 'accepted' | 'rejected';

export type InvoiceTemplateCreate = {
    name: string;
    kind: InvoiceTemplateKind;
    is_active?: boolean;
    built_in_id?: (string | null);
    custom_data?: ({
    [key: string]: unknown;
} | null);
    imported_html?: (string | null);
    imported_pdf_data_url?: (string | null);
    imported_excel_columns?: ({
    [key: string]: unknown;
} | null);
    imported_excel_data?: (Array<{
    [key: string]: unknown;
}> | null);
};

export type InvoiceTemplateKind = 'built_in' | 'custom' | 'imported_html' | 'imported_pdf' | 'imported_excel';

export type InvoiceTemplatePublic = {
    name: string;
    kind: InvoiceTemplateKind;
    is_active?: boolean;
    built_in_id?: (string | null);
    custom_data?: ({
    [key: string]: unknown;
} | null);
    imported_html?: (string | null);
    imported_pdf_data_url?: (string | null);
    imported_excel_columns?: ({
    [key: string]: unknown;
} | null);
    imported_excel_data?: (Array<{
    [key: string]: unknown;
}> | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type InvoiceTemplatesPublic = {
    data: Array<InvoiceTemplatePublic>;
    count: number;
};

export type InvoiceTemplateUpdate = {
    name?: (string | null);
    kind?: (InvoiceTemplateKind | null);
    is_active?: (boolean | null);
    built_in_id?: (string | null);
    custom_data?: ({
    [key: string]: unknown;
} | null);
    imported_html?: (string | null);
    imported_pdf_data_url?: (string | null);
    imported_excel_columns?: ({
    [key: string]: unknown;
} | null);
    imported_excel_data?: (Array<{
    [key: string]: unknown;
}> | null);
};

export type InvoiceUpdate = {
    invoice_number?: (string | null);
    document_type?: (DocumentType | null);
    invoice_date?: (string | null);
    due_date?: (string | null);
    valid_until?: (string | null);
    currency?: (string | null);
    subtotal?: (number | null);
    total_tax?: (number | null);
    grand_total?: (number | null);
    discount?: (number | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: (InvoiceStatus | null);
    place_of_supply?: (string | null);
    reverse_charge?: (boolean | null);
    customer_id?: (string | null);
    items?: (Array<InvoiceItemData> | null);
};

export type InvoiceWithCustomer = {
    invoice_number: string;
    document_type?: DocumentType;
    invoice_date: string;
    due_date?: (string | null);
    valid_until?: (string | null);
    currency?: string;
    subtotal?: number;
    total_tax?: number;
    grand_total?: number;
    discount?: number;
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: InvoiceStatus;
    place_of_supply?: (string | null);
    reverse_charge?: boolean;
    id: string;
    owner_id: string;
    customer_id: string;
    items?: Array<InvoiceItemData>;
    created_at: string;
    updated_at: string;
    customer?: (CustomerPublic | null);
};

export type ItemCreate = {
    name: string;
    description?: (string | null);
    category?: (string | null);
    sku?: (string | null);
    unit?: (string | null);
    price?: number;
    tax_rate?: number;
    stock?: number;
    low_stock_threshold?: number;
    stock_history?: Array<{
        [key: string]: unknown;
    }>;
};

export type ItemPublic = {
    name: string;
    description?: (string | null);
    category?: (string | null);
    sku?: (string | null);
    unit?: (string | null);
    price?: number;
    tax_rate?: number;
    stock?: number;
    low_stock_threshold?: number;
    stock_history?: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    name?: (string | null);
    description?: (string | null);
    category?: (string | null);
    sku?: (string | null);
    unit?: (string | null);
    price?: (number | null);
    tax_rate?: (number | null);
    stock?: (number | null);
    low_stock_threshold?: (number | null);
    stock_history?: (Array<{
    [key: string]: unknown;
}> | null);
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationCreate = {
    type?: NotificationType;
    title: string;
    description?: (string | null);
    table_id?: (string | null);
    table_name?: (string | null);
    row_id?: (string | null);
    row_label?: (string | null);
    read?: boolean;
    scheduled_for?: (string | null);
};

export type NotificationPublic = {
    type?: NotificationType;
    title: string;
    description?: (string | null);
    table_id?: (string | null);
    table_name?: (string | null);
    row_id?: (string | null);
    row_label?: (string | null);
    read?: boolean;
    scheduled_for?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
    unread_count: number;
};

export type NotificationType = 'reminder' | 'due_date' | 'expiry' | 'info';

export type NotificationUpdate = {
    read?: (boolean | null);
};

export type PaginatedResponse_DataTablePublic_ = {
    data: Array<unknown>;
    total: number;
    page: number;
    page_size: number;
    total_pages: number;
};

export type PaginatedResponse_UserPublic_ = {
    data: Array<unknown>;
    total: number;
    page: number;
    page_size: number;
    total_pages: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
    is_superuser?: boolean;
};

export type SendEmailRequest = {
    to_email: string;
    subject?: string;
};

export type SendReminderRequest = {
    to_phone: string;
    days_overdue?: (number | null);
};

export type SendWhatsAppRequest = {
    to_phone: string;
};

export type TableReminderCreate = {
    reminder_data: {
        [key: string]: unknown;
    };
};

export type TableReminderPublic = {
    reminder_data: {
        [key: string]: unknown;
    };
    id: string;
    table_id: string;
    created_at: string;
};

export type TableRowCreate = {
    data: {
        [key: string]: unknown;
    };
};

export type TableRowPublic = {
    data: {
        [key: string]: unknown;
    };
    id: string;
    table_id: string;
    created_at: string;
};

export type TableRowUpdate = {
    data: {
        [key: string]: unknown;
    };
};

export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
    expires_in?: (number | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    is_verified?: boolean;
    avatar_url?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminListUsersData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type AdminListUsersResponse = (PaginatedResponse_UserPublic_);

export type AdminCreateUserData = {
    accessToken?: (string | null);
    requestBody: AdminUserCreate;
};

export type AdminCreateUserResponse = (UserPublic);

export type AdminGetUserData = {
    accessToken?: (string | null);
    userId: string;
};

export type AdminGetUserResponse = (UserPublic);

export type AdminUpdateUserData = {
    accessToken?: (string | null);
    requestBody: AdminUserUpdate;
    userId: string;
};

export type AdminUpdateUserResponse = (UserPublic);

export type AdminDeleteUserData = {
    accessToken?: (string | null);
    userId: string;
};

export type AdminDeleteUserResponse = (void);

export type AuthSignupData = {
    requestBody: UserRegister;
};

export type AuthSignupResponse = (AuthResponse);

export type AuthLoginData = {
    requestBody: LoginRequest;
};

export type AuthLoginResponse = (AuthResponse);

export type AuthRefreshTokenData = {
    refreshToken?: (string | null);
};

export type AuthRefreshTokenResponse = (Token);

export type AuthLogoutResponse = (Message);

export type AuthGetCurrentUserInfoData = {
    accessToken?: (string | null);
};

export type AuthGetCurrentUserInfoResponse = (UserPublic);

export type AuthUpdateCurrentUserData = {
    accessToken?: (string | null);
    requestBody: UserUpdateMe;
};

export type AuthUpdateCurrentUserResponse = (UserPublic);

export type AuthForgotPasswordData = {
    email: string;
};

export type AuthForgotPasswordResponse = (Message);

export type AuthResetPasswordData = {
    requestBody: NewPassword;
};

export type AuthResetPasswordResponse = (Message);

export type AuthUpdatePasswordData = {
    accessToken?: (string | null);
    requestBody: UpdatePassword;
};

export type AuthUpdatePasswordResponse = (Message);

export type CompanySettingsGetCompanySettingsData = {
    accessToken?: (string | null);
};

export type CompanySettingsGetCompanySettingsResponse = (CompanySettingsPublic);

export type CompanySettingsCreateCompanySettingsData = {
    accessToken?: (string | null);
    requestBody: CompanySettingsCreate;
};

export type CompanySettingsCreateCompanySettingsResponse = (CompanySettingsPublic);

export type CompanySettingsUpdateCompanySettingsData = {
    accessToken?: (string | null);
    requestBody: CompanySettingsUpdate;
};

export type CompanySettingsUpdateCompanySettingsResponse = (CompanySettingsPublic);

export type CompanySettingsDeleteCompanySettingsData = {
    accessToken?: (string | null);
};

export type CompanySettingsDeleteCompanySettingsResponse = (void);

export type CustomersReadCustomersData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type CustomersReadCustomersResponse = (CustomersPublic);

export type CustomersCreateCustomerData = {
    accessToken?: (string | null);
    requestBody: CustomerCreate;
};

export type CustomersCreateCustomerResponse = (CustomerPublic);

export type CustomersReadCustomerData = {
    accessToken?: (string | null);
    id: string;
};

export type CustomersReadCustomerResponse = (CustomerPublic);

export type CustomersUpdateCustomerData = {
    accessToken?: (string | null);
    id: string;
    requestBody: CustomerUpdate;
};

export type CustomersUpdateCustomerResponse = (CustomerPublic);

export type CustomersDeleteCustomerData = {
    accessToken?: (string | null);
    id: string;
};

export type CustomersDeleteCustomerResponse = (void);

export type HealthResponse = ({
    [key: string]: (string);
});

export type SentryDebugResponse = ({
    [key: string]: (string);
});

export type InvoicesGetDashboardStatsData = {
    accessToken?: (string | null);
    documentType?: (DocumentType | null);
};

export type InvoicesGetDashboardStatsResponse = (DashboardStats);

export type InvoicesReadInvoicesData = {
    accessToken?: (string | null);
    customerId?: (string | null);
    documentType?: (DocumentType | null);
    limit?: number;
    skip?: number;
    status?: (InvoiceStatus | null);
};

export type InvoicesReadInvoicesResponse = (InvoicesPublic);

export type InvoicesCreateInvoiceData = {
    accessToken?: (string | null);
    requestBody: InvoiceCreate;
};

export type InvoicesCreateInvoiceResponse = (InvoicePublic);

export type InvoicesReadInvoiceData = {
    accessToken?: (string | null);
    id: string;
};

export type InvoicesReadInvoiceResponse = (InvoiceWithCustomer);

export type InvoicesUpdateInvoiceData = {
    accessToken?: (string | null);
    id: string;
    requestBody: InvoiceUpdate;
};

export type InvoicesUpdateInvoiceResponse = (InvoicePublic);

export type InvoicesDeleteInvoiceData = {
    accessToken?: (string | null);
    id: string;
};

export type InvoicesDeleteInvoiceResponse = (void);

export type InvoicesSendInvoiceEmailData = {
    accessToken?: (string | null);
    id: string;
    requestBody: SendEmailRequest;
};

export type InvoicesSendInvoiceEmailResponse = ({
    [key: string]: (string);
});

export type InvoicesSendInvoiceWhatsappData = {
    accessToken?: (string | null);
    id: string;
    requestBody: SendWhatsAppRequest;
};

export type InvoicesSendInvoiceWhatsappResponse = ({
    [key: string]: unknown;
});

export type InvoicesSendInvoiceReminderData = {
    accessToken?: (string | null);
    id: string;
    requestBody: SendReminderRequest;
};

export type InvoicesSendInvoiceReminderResponse = ({
    [key: string]: unknown;
});

export type InvoiceTemplatesReadInvoiceTemplatesData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type InvoiceTemplatesReadInvoiceTemplatesResponse = (InvoiceTemplatesPublic);

export type InvoiceTemplatesCreateInvoiceTemplateData = {
    accessToken?: (string | null);
    requestBody: InvoiceTemplateCreate;
};

export type InvoiceTemplatesCreateInvoiceTemplateResponse = (InvoiceTemplatePublic);

export type InvoiceTemplatesReadActiveInvoiceTemplateData = {
    accessToken?: (string | null);
};

export type InvoiceTemplatesReadActiveInvoiceTemplateResponse = (InvoiceTemplatePublic);

export type InvoiceTemplatesReadInvoiceTemplateData = {
    accessToken?: (string | null);
    id: string;
};

export type InvoiceTemplatesReadInvoiceTemplateResponse = (InvoiceTemplatePublic);

export type InvoiceTemplatesUpdateInvoiceTemplateData = {
    accessToken?: (string | null);
    id: string;
    requestBody: InvoiceTemplateUpdate;
};

export type InvoiceTemplatesUpdateInvoiceTemplateResponse = (InvoiceTemplatePublic);

export type InvoiceTemplatesDeleteInvoiceTemplateData = {
    accessToken?: (string | null);
    id: string;
};

export type InvoiceTemplatesDeleteInvoiceTemplateResponse = (void);

export type InvoiceTemplatesActivateInvoiceTemplateData = {
    accessToken?: (string | null);
    id: string;
};

export type InvoiceTemplatesActivateInvoiceTemplateResponse = (InvoiceTemplatePublic);

export type InvoiceTemplatesParseExcelPreviewData = {
    accessToken?: (string | null);
    formData: Body_invoice_templates_parse_excel_preview;
};

export type InvoiceTemplatesParseExcelPreviewResponse = (ExcelParseResponse);

export type ItemsReadItemsData = {
    accessToken?: (string | null);
    category?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    stockStatus?: (string | null);
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    accessToken?: (string | null);
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsListCategoriesData = {
    accessToken?: (string | null);
};

export type ItemsListCategoriesResponse = (Array<(string)>);

export type ItemsReadItemData = {
    accessToken?: (string | null);
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    accessToken?: (string | null);
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    accessToken?: (string | null);
    id: string;
};

export type ItemsDeleteItemResponse = (void);

export type ItemsAdjustStockData = {
    accessToken?: (string | null);
    id: string;
    quantity: number;
    reason?: (string | null);
    reference?: (string | null);
};

export type ItemsAdjustStockResponse = (ItemPublic);

export type NotificationsGetNotificationsData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
    type?: (NotificationType | null);
    unreadOnly?: boolean;
};

export type NotificationsGetNotificationsResponse = (NotificationsPublic);

export type NotificationsCreateNotificationData = {
    accessToken?: (string | null);
    requestBody: NotificationCreate;
};

export type NotificationsCreateNotificationResponse = (NotificationPublic);

export type NotificationsClearAllData = {
    accessToken?: (string | null);
};

export type NotificationsClearAllResponse = (void);

export type NotificationsGetNotificationData = {
    accessToken?: (string | null);
    id: string;
};

export type NotificationsGetNotificationResponse = (NotificationPublic);

export type NotificationsUpdateNotificationData = {
    accessToken?: (string | null);
    id: string;
    requestBody: NotificationUpdate;
};

export type NotificationsUpdateNotificationResponse = (NotificationPublic);

export type NotificationsDeleteNotificationData = {
    accessToken?: (string | null);
    id: string;
};

export type NotificationsDeleteNotificationResponse = (void);

export type NotificationsMarkAllReadData = {
    accessToken?: (string | null);
};

export type NotificationsMarkAllReadResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TablesListTablesData = {
    accessToken?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type TablesListTablesResponse = (PaginatedResponse_DataTablePublic_);

export type TablesCreateTableData = {
    accessToken?: (string | null);
    requestBody: DataTableCreate;
};

export type TablesCreateTableResponse = (DataTablePublic);

export type TablesGetTableData = {
    accessToken?: (string | null);
    tableId: string;
};

export type TablesGetTableResponse = (DataTableWithRows);

export type TablesUpdateTableData = {
    accessToken?: (string | null);
    requestBody: DataTableUpdate;
    tableId: string;
};

export type TablesUpdateTableResponse = (DataTablePublic);

export type TablesDeleteTableData = {
    accessToken?: (string | null);
    tableId: string;
};

export type TablesDeleteTableResponse = (void);

export type TablesDuplicateTableData = {
    accessToken?: (string | null);
    tableId: string;
};

export type TablesDuplicateTableResponse = (DataTablePublic);

export type TablesCreateTableRowData = {
    accessToken?: (string | null);
    requestBody: TableRowCreate;
    tableId: string;
};

export type TablesCreateTableRowResponse = (TableRowPublic);

export type TablesUpdateTableRowData = {
    accessToken?: (string | null);
    requestBody: TableRowUpdate;
    rowId: string;
    tableId: string;
};

export type TablesUpdateTableRowResponse = (TableRowPublic);

export type TablesDeleteTableRowData = {
    accessToken?: (string | null);
    rowId: string;
    tableId: string;
};

export type TablesDeleteTableRowResponse = (void);

export type TablesBulkDeleteTableRowsData = {
    accessToken?: (string | null);
    requestBody: Array<(string)>;
    tableId: string;
};

export type TablesBulkDeleteTableRowsResponse = (BulkDeleteResponse);

export type TablesCreateTableReminderData = {
    accessToken?: (string | null);
    requestBody: TableReminderCreate;
    tableId: string;
};

export type TablesCreateTableReminderResponse = (TableReminderPublic);

export type TablesDeleteTableReminderData = {
    accessToken?: (string | null);
    reminderId: string;
    tableId: string;
};

export type TablesDeleteTableReminderResponse = (void);

export type UsersReadUsersData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeData = {
    accessToken?: (string | null);
};

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    accessToken?: (string | null);
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersDeleteUserMeData = {
    accessToken?: (string | null);
};

export type UsersDeleteUserMeResponse = (void);

export type UsersReadUserByIdData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    accessToken?: (string | null);
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersDeleteUserResponse = (void);

export type UtilsTestEmailData = {
    accessToken?: (string | null);
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);