// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CustomerCreate = {
    name: string;
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    gst?: (string | null);
    state?: (string | null);
    notes?: (string | null);
};

export type CustomerPublic = {
    name: string;
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    gst?: (string | null);
    state?: (string | null);
    notes?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type CustomersPublic = {
    data: Array<CustomerPublic>;
    count: number;
};

export type CustomerUpdate = {
    name?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    gst?: (string | null);
    state?: (string | null);
    notes?: (string | null);
};

export type DashboardStats = {
    total_invoices?: number;
    paid_count?: number;
    unpaid_count?: number;
    overdue_count?: number;
    total_customers?: number;
    total_revenue?: number;
};

export type DataTableColumn = {
    name: string;
    description?: (string | null);
    type: string;
    mandatory?: boolean;
    options?: Array<(string)>;
};

export type DataTableCreate = {
    name: string;
    description?: (string | null);
    columns: Array<DataTableColumn>;
};

export type DataTablePublic = {
    name: string;
    description?: (string | null);
    columns: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type DataTableUpdate = {
    name?: (string | null);
    description?: (string | null);
    columns?: (Array<DataTableColumn> | null);
};

export type DataTableWithRows = {
    name: string;
    description?: (string | null);
    columns: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    rows: Array<TableRowPublic>;
    reminders: Array<TableReminderPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InvoiceCreate = {
    invoice_number: string;
    invoice_date: string;
    due_date?: (string | null);
    currency?: string;
    subtotal?: number;
    total_tax?: number;
    grand_total?: number;
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: InvoiceStatus;
    customer_id: string;
    items?: Array<InvoiceItemData>;
};

/**
 * Schema for a single line item embedded in the invoice JSONB.
 */
export type InvoiceItemData = {
    name: string;
    description?: (string | null);
    quantity?: number;
    price?: number;
    tax?: number;
};

export type InvoicePublic = {
    invoice_number: string;
    invoice_date: string;
    due_date?: (string | null);
    currency?: string;
    subtotal?: number;
    total_tax?: number;
    grand_total?: number;
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: InvoiceStatus;
    id: string;
    owner_id: string;
    customer_id: string;
    items?: Array<InvoiceItemData>;
    created_at: string;
    updated_at: string;
};

export type InvoicesPublic = {
    data: Array<InvoicePublic>;
    count: number;
};

export type InvoiceStatus = 'unpaid' | 'paid' | 'overdue';

export type InvoiceUpdate = {
    invoice_date?: (string | null);
    due_date?: (string | null);
    currency?: (string | null);
    subtotal?: (number | null);
    total_tax?: (number | null);
    grand_total?: (number | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: (InvoiceStatus | null);
    customer_id?: (string | null);
    items?: (Array<InvoiceItemData> | null);
};

export type InvoiceWithCustomer = {
    invoice_number: string;
    invoice_date: string;
    due_date?: (string | null);
    currency?: string;
    subtotal?: number;
    total_tax?: number;
    grand_total?: number;
    notes?: (string | null);
    payment_terms?: (string | null);
    status?: InvoiceStatus;
    id: string;
    owner_id: string;
    customer_id: string;
    items?: Array<InvoiceItemData>;
    created_at: string;
    updated_at: string;
    customer?: (CustomerPublic | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PaginatedResponse_DataTablePublic_ = {
    data: Array<unknown>;
    total: number;
    page: number;
    page_size: number;
    total_pages: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TableReminderCreate = {
    reminder_data: {
        [key: string]: unknown;
    };
};

export type TableReminderPublic = {
    reminder_data: {
        [key: string]: unknown;
    };
    id: string;
    table_id: string;
    created_at: string;
};

export type TableRowCreate = {
    data: {
        [key: string]: unknown;
    };
};

export type TableRowPublic = {
    data: {
        [key: string]: unknown;
    };
    id: string;
    table_id: string;
    created_at: string;
};

export type TableRowUpdate = {
    data: {
        [key: string]: unknown;
    };
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CustomersReadCustomersData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type CustomersReadCustomersResponse = (CustomersPublic);

export type CustomersCreateCustomerData = {
    accessToken?: (string | null);
    requestBody: CustomerCreate;
};

export type CustomersCreateCustomerResponse = (CustomerPublic);

export type CustomersReadCustomerData = {
    accessToken?: (string | null);
    id: string;
};

export type CustomersReadCustomerResponse = (CustomerPublic);

export type CustomersUpdateCustomerData = {
    accessToken?: (string | null);
    id: string;
    requestBody: CustomerUpdate;
};

export type CustomersUpdateCustomerResponse = (CustomerPublic);

export type CustomersDeleteCustomerData = {
    accessToken?: (string | null);
    id: string;
};

export type CustomersDeleteCustomerResponse = (Message);

export type InvoicesGetDashboardStatsData = {
    accessToken?: (string | null);
};

export type InvoicesGetDashboardStatsResponse = (DashboardStats);

export type InvoicesReadInvoicesData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
    status?: (InvoiceStatus | null);
};

export type InvoicesReadInvoicesResponse = (InvoicesPublic);

export type InvoicesCreateInvoiceData = {
    accessToken?: (string | null);
    requestBody: InvoiceCreate;
};

export type InvoicesCreateInvoiceResponse = (InvoicePublic);

export type InvoicesReadInvoiceData = {
    accessToken?: (string | null);
    id: string;
};

export type InvoicesReadInvoiceResponse = (InvoiceWithCustomer);

export type InvoicesUpdateInvoiceData = {
    accessToken?: (string | null);
    id: string;
    requestBody: InvoiceUpdate;
};

export type InvoicesUpdateInvoiceResponse = (InvoicePublic);

export type InvoicesDeleteInvoiceData = {
    accessToken?: (string | null);
    id: string;
};

export type InvoicesDeleteInvoiceResponse = (Message);

export type ItemsReadItemsData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    accessToken?: (string | null);
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    accessToken?: (string | null);
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    accessToken?: (string | null);
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    accessToken?: (string | null);
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenData = {
    accessToken?: (string | null);
};

export type LoginTestTokenResponse = (UserPublic);

export type LoginRefreshTokenData = {
    refreshToken?: (string | null);
};

export type LoginRefreshTokenResponse = (Token);

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    accessToken?: (string | null);
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TablesListTablesData = {
    accessToken?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type TablesListTablesResponse = (PaginatedResponse_DataTablePublic_);

export type TablesCreateTableData = {
    accessToken?: (string | null);
    requestBody: DataTableCreate;
};

export type TablesCreateTableResponse = (DataTablePublic);

export type TablesGetTableData = {
    accessToken?: (string | null);
    tableId: string;
};

export type TablesGetTableResponse = (DataTableWithRows);

export type TablesUpdateTableData = {
    accessToken?: (string | null);
    requestBody: DataTableUpdate;
    tableId: string;
};

export type TablesUpdateTableResponse = (DataTablePublic);

export type TablesDeleteTableData = {
    accessToken?: (string | null);
    tableId: string;
};

export type TablesDeleteTableResponse = (void);

export type TablesDuplicateTableData = {
    accessToken?: (string | null);
    tableId: string;
};

export type TablesDuplicateTableResponse = (DataTablePublic);

export type TablesCreateTableRowData = {
    accessToken?: (string | null);
    requestBody: TableRowCreate;
    tableId: string;
};

export type TablesCreateTableRowResponse = (TableRowPublic);

export type TablesUpdateTableRowData = {
    accessToken?: (string | null);
    requestBody: TableRowUpdate;
    rowId: string;
    tableId: string;
};

export type TablesUpdateTableRowResponse = (TableRowPublic);

export type TablesDeleteTableRowData = {
    accessToken?: (string | null);
    rowId: string;
    tableId: string;
};

export type TablesDeleteTableRowResponse = (void);

export type TablesBulkDeleteTableRowsData = {
    accessToken?: (string | null);
    requestBody: Array<(string)>;
    tableId: string;
};

export type TablesBulkDeleteTableRowsResponse = (unknown);

export type TablesCreateTableReminderData = {
    accessToken?: (string | null);
    requestBody: TableReminderCreate;
    tableId: string;
};

export type TablesCreateTableReminderResponse = (TableReminderPublic);

export type TablesDeleteTableReminderData = {
    accessToken?: (string | null);
    reminderId: string;
    tableId: string;
};

export type TablesDeleteTableReminderResponse = (void);

export type UsersReadUsersData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    accessToken?: (string | null);
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    accessToken?: (string | null);
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersReadUserMeData = {
    accessToken?: (string | null);
};

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeData = {
    accessToken?: (string | null);
};

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdatePasswordMeData = {
    accessToken?: (string | null);
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    accessToken?: (string | null);
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    accessToken?: (string | null);
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    accessToken?: (string | null);
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);